### ISSUE TITLE
5 months ago this brilliance was created - can you tell us all how to make colored boxes responsive?

### ISSUE THREAD

**Issue by tweed** [chinchang/cta.js#15]
Flexbox in the middle part would be great (the colored boxes that open/animate section) -- really interested in flexbox

PROBLEM: when the browser is made small the boxes all cram together.

Question: Is there a way to have them align all in a row when browser LARGE -- ie. setting a width i guess?

SO: then when the browser is small they would be one above the other.

Can you help us all with this? Grid needed i think.

whatever happens great thanks!

Don

**Comment by chinchang** [comment]
This is unrelated to the library itself, though here is what you can do:

When browser width goes below your threshold width, make all boxes -> `width: 100%`
