### ISSUE TITLE
Not compatible with bootstrap

### ISSUE THREAD

**Issue by ashwinkshenoy** [chinchang/cta.js#7]
This animation is awesome , but it is not compatible with bootstrap.(especially the closing part)

**Comment by chinchang** [comment]
Can you show a test case on jsbin, jsfiddle somewhere?

**Comment by davedele** [comment]
Rename the class ".modal" in the index file. Bootstrap has a class by the same name by default. So either remove the class declarations from bootstrap or the later..

**Comment by davedele** [comment]
If you don't change this the exiting animation will start from the top left every time it fires:
Here is the BS class to remove:
 .modal {
  position: fixed;
  top: 10%;
  left: 50%;
  z-index: 1050;
  width: 560px;
  margin-left: -280px;
  background-color: #ffffff;
  border: 1px solid #999;
  border: 1px solid rgba(0, 0, 0, 0.3);
  *border: 1px solid #999;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
  outline: none;
  -webkit-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
     -moz-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
          box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
  -webkit-background-clip: padding-box;
     -moz-background-clip: padding-box;
          background-clip: padding-box;
}

**Comment by ashwinkshenoy** [comment]
Here's the fiddle
https://jsfiddle.net/r5mmen8c/

**Comment by davedele** [comment]
You haven't removed or renamed that .modal class.. As I said earlier, bootstrap has a class with the same name. Remove that class from bootstrap or rename it in the css file you made..

**Comment by chinchang** [comment]
As @davedele said, you can rename the modal class in the cta.js example. The `display: none` in bootstrap's `.modal` class interferes with the animation. Tried it, it works.
